---
apiVersion: v1
kind: Service
metadata:
  name: my-api-service
  namespace: demo-system
  labels:
    app: demo
    group: api
    role: api-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: demo
    group: api
    role: api-manager