---
apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  namespace: demo-system
  labels:
    app: demo
    group: api
    role: api-manager

spec:
  containers:
  - name: api-pod
    imagePullPolicy: "IfNotPresent"
    image: my-app:latest
    resources:
      limits:
        memory: "1024Mi"
        cpu: "500m"
    command: [ "/app" ]
    env:
      - name: MYSQL_USER
        value: demo-user
      - name: MYSQL_PASSWORD
        value: D3m0-P4ssW0rD?
      - name: MYSQL_HOST
        value: my-database-service
      - name: MYSQL_PORT
        value: "3306"
      - name: MYSQL_DATABASE
        value: demo-database