---
apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  namespace: demo-system
  labels:
    app: demo
    group: api
    role: api-manager

spec:
  containers:
  - name: api-pod
    image: alpine:latest
    resources:
      limits:
        memory: "1024Mi"
        cpu: "500m"
    command: [ "/bin/sh" ]
    args:
      - "-c"
      - "apk add --no-cache mysql-client && mysql -u $MYSQL_USER -p{$MYSQL_PASSWORD} -h $MYSQL_HOST"
    env:
      - name: MYSQL_USER
        value: demo-user
      - name: MYSQL_PASSWORD
        value: D3m0-P4ssW0rD?
      - name: MYSQL_HOST
        value: my-database-service