---
apiVersion: v1
kind: Service
metadata:
  name: my-database-service
  namespace: demo-system
  labels:
    app: demo
    group: database
    role: data-service
spec:
  ports:
    - port: 3306
  selector:
    app: demo
    group: database
    role: data-manager
  clusterIP: None