---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-database-volume
  namespace: demo-system
  labels:
    app: demo
    group: database
    role: data-storage
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/data"
  persistentVolumeReclaimPolicy: Delete